# .github/workflows/python-version.yml

## Name of the workflow.
name: Python version
## Set the trigger policy.
## In this case, the workflow will execute on a push event,
## or when a nwe commit is pushed to the repository
on: [push]
## List the steps to be executed by the workflow
jobs:
  ## Set the name of the job
  check-python-version:
    ## Configure the operating system the workflow shoudl run on 
    ## In this case, the job on Ubuntu
    runs-on: ubuntu-latest
    ## Define a sequence of steps tp be executed
    steps:
      ## Use the public 'checkout' action in version v2
      ## to checkout the existing code in the repository
      - uses: actions/checkout@v2
      ## Use the public 'setup-python' action in version v2
      ## to install python on the ubuntu based based environement
      - uses: actions/setup-python@v2
      ## Executes the 'python --version' command
      - run: python --version